routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('welcome');

Auth::routes();

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    /**
     * Group
     */
    Route::resource('group', 'GroupController', ['except' => [
        'destroy'
    ]]);

    /**
     * Featured
     */
    Route::get('featured/{group}/create', 'FeaturedController@create')->name('featured.create');
    Route::post('featured/{group}/store', 'FeaturedController@store')->name('featured.store');
    Route::resource('featured', 'FeaturedController', ['except' => [
        'create', 'store', 'destroy'
    ]]);

    /**
     * Ads
     */
    Route::resource('ad', 'AdController', ['except' => [
        'destroy'
    ]]);

    /**
     * Settings
     */
    Route::get('settings', 'SettingsController@show')->name('settings.show');
    Route::put('settings', 'SettingsController@update')->name('settings.update');

    /**
     * Docs
     */
    Route::get('api/docs', function () {
        return view('admin.docs.index');
    })->name('docs');
});

app/Group.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;

class Group extends Model {
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['name', 'icon_url'];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['created_at', 'updated_at'];

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = true;

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function featured() {
        return $this->hasMany('\App\Featured', 'group_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function featuredActive() {
        return $this->hasMany('\App\Featured', 'group_id', 'id')->where('active', true);
    }
}

app/Http/Controllers/GroupController.php
<?php

namespace App\Http\Controllers;

use App\Group;
use App\Helpers\Constant;
use App\Http\Requests\CreateGroupRequest;
use Illuminate\Http\Request;
use Intervention\Image\Facades\Image;

class GroupController extends Controller {

    /**
     * GroupController constructor.
     */
    public function __construct() {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $groups = Group::all();
        return view('admin.group.index', ['groups' => $groups]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $group = new Group;
        return view('admin.group.create', ['group' => $group]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateGroupRequest $request) {
        $group = new Group;
        $group->fill($request->all());
        $image = $request->image;
        $filePath = Constant::ASSETS_PATH . '/img/groups/' . $image->getClientOriginalName() . '.' . $image->getClientOriginalExtension();
        Image::make($image)->resize(71, 71)->save(public_path($filePath));
        $group->icon_url = $filePath;
        $group->save();
        return redirect()->route('group.index');
    }

    /**
     * Display the specified resource.
     *
     * @param Request $request
     * @param Group $group
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Request $request, Group $group) {

        $active = $request->has('active');
        $search = $request->has('search');

        $group->load(['featured' => function($query) use ($request, $search, $active) {
            $searchTerm = $request->get('search');
            $activeTerm = $request->get('active');
            $isNotEmpty = ($activeTerm==0 || $activeTerm==1) && $activeTerm!='';

            if($search && !empty($searchTerm))
                $query->where('name', 'LIKE', '%'.$searchTerm.'%')->get();
            if($active && $isNotEmpty)
                $query->where('active', $activeTerm == 1);
        }, 'featured.thumbnail', 'featured.images']);

        return view('admin.group.single-view', ['group' => $group]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        //
    }
}

resources/views/admin/group/create.blade.php
@extends('layouts.admin')

@section('content')
<div class="container">
    <div class="row text-center">
        <div class="col-md-12">
            <div class="title m-b-md">
                Placebook
            </div>
        </div>
    </div>
    <div class="row text-center">
        <div class="col-md-offset-3 col-md-6">
            <div class="links">
                <p class="col-md-3 col-xs-6"><a href="{{ route('group.index') }}" class="active">Grupe</a></p>
                <p class="col-md-3 col-xs-6"><a href="{{ route('featured.index') }}">Sponzorisani</a></p>
                <p class="col-md-3 col-xs-6"><a href="{{ route('ad.index') }}">Reklame</a></p>
                <p class="col-md-3 col-xs-6"><a href="{{ route('settings.show') }}">Podešavanja</a></p>
            </div>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <h1>Dodavanje grupe</h1>
        </div>
    </div>
    <hr>
    @if (count($errors) > 0)
    <div class="row">
        <div class="col-md-offset-2 col-md-8">
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li class="normal-font">{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        </div>
    </div>
    @endif
    <div class="row">
        <div class="col-md-10">
            {{ Form::model($group, ['route' => 'group.store', 'class' => 'form-horizontal', 'method' => 'POST', 'files' => true]) }}
                <div class="form-group">
                    {{ Form::label('name', 'Ime grupe', ['class' => 'col-sm-2 control-label']) }}
                    <div class="col-sm-10">
                        {{ Form::text('name', old('name'), ['class' => 'form-control', 'placeholder' => 'Ime grupe']) }}
                    </div>
                </div>
                <div class="form-group">
                    {{ Form::label('image', 'Logo slika', ['class' => 'col-sm-2 control-label']) }}
                    <div class="col-sm-10">
                        {{ Form::file('image', []) }}
                        <p class="help-block"><strong>* Logo slika grupe. (71x71 u pikselima)</strong></p>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        {{ Form::submit('Kreiraj', ['class' => 'btn btn-primary']) }}
                    </div>
                </div>
            {{ Form::close() }}
        </div>
    </div>
</div>
@endsection

resources/views/admin/group/index.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <div class="title m-b-md">
                    Placebook
                </div>
            </div>
        </div>
        <div class="row text-center">
            <div class="col-md-offset-3 col-md-6">
                <div class="links">
                    <p class="col-md-3 col-xs-6"><a href="{{ route('group.create') }}" class="active">Dodaj Grupu</a></p>
                    <p class="col-md-3 col-xs-6"><a href="{{ route('featured.index') }}">Sponzorisani</a></p>
                    <p class="col-md-3 col-xs-6"><a href="{{ route('ad.index') }}">Reklame</a></p>
                    <p class="col-md-3 col-xs-6"><a href="{{ route('settings.show') }}">Podešavanja</a></p>
                </div>
            </div>
        </div>
        <hr>
        <div class="row">
            @foreach($groups as $group)
                <div class="col-md-4">
                    <a href="{{ route('group.show', ['group' => $group]) }}" class="text-center">
                        <img class="img-responsive center-block img-circle blue-background" src="{{ asset($group->icon_url) }}" alt="{{ $group->name }}">
                        <h2>{{ $group->name }}</h2>
                    </a>
                </div>
                @if($loop->iteration%3==0)
                <hr class="col-md-12">
                @endif
            @endforeach
        </div>
    </div>
@endsection

resources/views/admin/group/single-view.blade.php
@extends('layouts.admin')

@section('content')
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">
                <div class="title m-b-md">
                    Placebook
                </div>
            </div>
        </div>
        <div class="row text-center">
            <div class="col-md-offset-3 col-md-6">
                <div class="links">
                    <p class="col-md-3 col-xs-6"><a href="{{ route('group.index') }}" class="active">Grupe</a></p>
                    <p class="col-md-3 col-xs-6"><a href="{{ route('featured.create', ['group' => $group]) }}">Dodaj objekat</a></p>
                    <p class="col-md-3 col-xs-6"><a href="{{ route('ad.index') }}">Reklame</a></p>
                    <p class="col-md-3 col-xs-6"><a href="{{ route('settings.show') }}">Podešavanja</a></p>
                </div>
            </div>
        </div>
        <hr>
        <h2 class="text-center">{{ $group->name }}</h2>
        <hr>
        <div class="row">
            <div class="col-md-2 col-md-push-10 clearfix">
                {{ Form::open(['route' => ['group.show', $group], 'method' => 'GET', 'class' => 'form-horizontal']) }}
                <div class="form-group">
                    {{ Form::select('active', [null => 'Svi', 1 => 'Aktivne', 0 => 'Neaktivne'], request()->get('active'), ['class' => 'form-control']) }}
                </div>
                <div class="form-group">
                    {{ Form::text('search', request()->get('search'), ['class' => 'form-control', 'placeholder' => 'Traženi pojam']) }}
                </div>
                <div class="form-group pull-right">
                    {{ Form::submit('Pretraži', ['class' => 'btn btn-success']) }}
                </div>
                <div class="form-group pull-left">
                    <a class="btn btn-default" href="{{ route('group.show', $group) }}">Očisti</a>
                </div>
            </div>
            <div class="col-md-10 col-md-pull-2">
                @if($group->featured->count()>0)
                    @foreach($group->featured as $feature)
                        @if($loop->iteration%4==1)
                        <div class="row">
                        @endif
                        <div class="col-sm-4 col-md-3 text-center">
                            <a href="{{ route('featured.show', ['featured' => $feature]) }}">
                                <img class="img-responsive center-block" src="{{ asset($feature->thumbnail->url) }}" alt="{{ $feature->name }}">
                                <h2>{{ $feature->name }}</h2>
                            </a>
                        </div>
                        @if($loop->iteration%4==0 || $loop->last)
                        </div>
                        @endif
                    @endforeach
                @else
                    <p class="lead">Nema pronađenih objekata za ovu grupu.</p>
                @endif
            </div>
        </div>
    </div>
@endsection